workflows:
  ios:
    name: Build iOS App
    scripts:
      - name: Install Dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Build with Xcode
        script: |
          xcodebuild -workspace StudyOs.xcworkspace -scheme StudyOs -configuration Release -archivePath $WORKSPACE_PATH/StudyOs.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $WORKSPACE_PATH/StudyOs.xcarchive -exportPath $WORKSPACE_PATH/StudyOs.ipa -exportOptionsPlist ExportOptions.plist
    artifacts:
      - $WORKSPACE_PATH/StudyOs.ipa